#!/bin/bash

echo "🔍 Debugging GitHub Actions Deployment"
echo "====================================="
echo ""
echo "Common issues and solutions:"
echo ""
echo "1. Security Group Issues:"
echo "   - Make sure AWS_SECURITY_GROUP_ID is correct (starts with sg-)"
echo "   - Verify IAM user has permission to modify security group"
echo "   - Check if security group exists in the correct region"
echo ""
echo "2. SSH Key Issues:"
echo "   - Make sure EC2_SSH_KEY contains the FULL PEM file content"
echo "   - Include -----BEGIN and -----END lines"
echo "   - No extra spaces or newlines"
echo ""
echo "3. Region Issues:"
echo "   - Make sure AWS_DEFAULT_REGION matches your EC2 region"
echo "   - Common regions: us-east-1, us-west-2, ap-southeast-1"
echo ""
echo "4. Quick Test Commands:"
echo "   # Test AWS CLI access:"
echo "   aws ec2 describe-security-groups --group-ids sg-xxxxxxxxx"
echo ""
echo "   # Test SSH access:"
echo "   ssh -i your-key.pem ubuntu@3.25.152.237 'echo test'"
echo ""
echo "5. Manual Security Group Fix:"
echo "   - Go to AWS Console → EC2 → Security Groups"
echo "   - Add rule: SSH (22) from 0.0.0.0/0 (temporary)"
echo "   - Test deployment again"
echo "   - Remove rule after testing"
