#!/bin/bash

echo "🔍 Adventure Chunk EC2 Diagnostic Script"
echo "========================================"
echo ""
echo "Run these commands on your EC2 server to diagnose the issue:"
echo ""
echo "1. Check if backend is running:"
echo "   pm2 status"
echo ""
echo "2. Check backend logs:"
echo "   pm2 logs adventure-chunk-api"
echo ""
echo "3. Check if API responds locally:"
echo "   curl http://localhost:8000/api/"
echo ""
echo "4. Check if API responds externally:"
echo "   curl http://3.25.152.237/api/"
echo ""
echo "5. Check nginx status:"
echo "   sudo systemctl status nginx"
echo ""
echo "6. Check what's in the current App.jsx:"
echo "   grep -n 'API_BASE_URL' /var/www/adventure-chunk/client/src/App.jsx"
echo ""
echo "7. Check what's in the built JS file:"
echo "   grep -o 'http://[^\"]*' /var/www/adventure-chunk/client/dist/assets/index-*.js | grep localhost"
echo ""
echo "8. Check the .env file:"
echo "   cat /var/www/adventure-chunk/client/.env"
echo ""
echo "9. Check nginx access logs for recent requests:"
echo "   sudo tail -10 /var/log/nginx/access.log"
echo ""
echo "10. Check nginx error logs:"
echo "    sudo tail -10 /var/log/nginx/error.log"
echo ""
echo "Run these and share the output so we can identify the exact issue!"
