#!/bin/bash

# Script to manually fix the EC2 server
echo "🔧 Manual EC2 Fix Script"
echo "========================="
echo ""
echo "Run these commands on your EC2 server:"
echo ""
echo "1. SSH into your EC2 instance:"
echo "   ssh -i your-key.pem ubuntu@3.25.152.237"
echo ""
echo "2. Pull the latest changes:"
echo "   cd /var/www/adventure-chunk"
echo "   git pull origin main"
echo ""
echo "3. Fix the App.jsx file (if needed):"
echo "   cd client/src"
echo "   sed -i \"s|const API_BASE_URL = 'http://localhost:8000';|const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';|g\" App.jsx"
echo ""
echo "4. Rebuild the frontend:"
echo "   cd /var/www/adventure-chunk/client"
echo "   npm run build"
echo ""
echo "5. Reload nginx:"
echo "   sudo systemctl reload nginx"
echo ""
echo "6. Test the app:"
echo "   curl http://3.25.152.237/"
echo ""
echo "✅ Your app should then work at http://3.25.152.237"
