#!/bin/bash

# Remote fix script - run this locally to fix the EC2 server
echo "🚀 Remote EC2 Fix Script"
echo "========================="
echo ""
echo "This script will help you fix the EC2 server without SSH."
echo ""
echo "Option 1: Quick test from your browser"
echo "1. Open: http://3.25.152.237"
echo "2. Open browser developer tools (F12)"
echo "3. Go to Console tab"
echo "4. Look for error messages"
echo "5. Go to Network tab and try to use the app"
echo "6. See what requests are failing"
echo ""
echo "Option 2: Test API directly"
echo "Run this command locally:"
echo "curl -X POST http://3.25.152.237/api/find-chunks -H \"Content-Type: application/json\" -d '{\"lat\":-37.840935,\"lon\":145.015794,\"drivetime\":30,\"chunkSize\":1}'"
echo ""
echo "Option 3: Create a simple test page"
echo "Create a file called test.html with this content:"
echo ""
echo "<!DOCTYPE html>"
echo "<html><head><title>API Test</title></head><body>"
echo "<h1>API Test</h1>"
echo "<button onclick=\"testAPI()\">Test API</button>"
echo "<div id=\"result\"></div>"
echo "<script>"
echo "function testAPI() {"
echo "  fetch('http://3.25.152.237/api/find-chunks', {"
echo "    method: 'POST',"
echo "    headers: {'Content-Type': 'application/json'}," 
echo "    body: JSON.stringify({lat: -37.840935, lon: 145.015794, drivetime: 30, chunkSize: 1})"
echo "  })"
echo "  .then(response => response.text())"
echo "  .then(data => document.getElementById('result').innerHTML = data)"
echo "  .catch(error => document.getElementById('result').innerHTML = 'Error: ' + error)"
echo "}"
echo "</script></body></html>"
echo ""
echo "Then open test.html in your browser and click the button."
echo ""
echo "This will help us identify if it's a frontend or backend issue!"
