#!/bin/bash

echo "🔐 GitHub Actions Secrets Setup"
echo "==============================="
echo ""
echo "To enable automatic deployment, you need to add these secrets to your GitHub repository:"
echo ""
echo "1. Go to your GitHub repository: https://github.com/YOUR_USERNAME/adventure-chunk"
echo "2. Click 'Settings' → 'Secrets and variables' → 'Actions'"
echo "3. Click 'New repository secret' for each of these:"
echo ""
echo "   EC2_HOST: 3.25.152.237"
echo "   EC2_USERNAME: ubuntu"
echo "   EC2_SSH_KEY: [Your private SSH key content]"
echo ""
echo "To get your SSH key content, run:"
echo "   cat ~/.ssh/id_rsa"
echo ""
echo "Or if you use a different key file:"
echo "   cat /path/to/your/private/key"
echo ""
echo "⚠️  IMPORTANT: Never commit your private SSH key to git!"
echo ""
echo "After adding these secrets, any push to main branch will automatically deploy to EC2!"
