#!/bin/bash

echo "🔍 SSH Key Verification"
echo "======================"
echo ""
echo "The deployment failed with SSH issues. Let's verify your setup:"
echo ""
echo "1. Check your PEM file format:"
echo "   cat ~/.ssh/your-key.pem | head -1"
echo "   (Should show: -----BEGIN RSA PRIVATE KEY----- or -----BEGIN PRIVATE KEY-----)"
echo ""
echo "2. Check your PEM file permissions:"
echo "   ls -la ~/.ssh/your-key.pem"
echo "   (Should show -rw-------)"
echo ""
echo "3. Test SSH connection manually:"
echo "   ssh -i ~/.ssh/your-key.pem ubuntu@3.25.152.237 'echo \"SSH connection works!\"'"
echo ""
echo "4. If the above works, your GitHub secret should be the FULL content:"
echo "   cat ~/.ssh/your-key.pem"
echo ""
echo "5. Make sure your EC2 security group allows SSH (port 22) from GitHub Actions IPs"
echo "   Current GitHub Actions IPs: https://api.github.com/meta"
echo ""
echo "Common issues:"
echo "- PEM file has wrong permissions (should be 600)"
echo "- GitHub secret is missing newlines"
echo "- Security group doesn't allow GitHub IPs"
echo "- Key file path is wrong"
